# backend-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: edwinistin/kubernetes-app-image:backend
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
---

# backend-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---

# backend-configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: demo-app
  labels:
    app: backend
data:
  MYSQL_HOST: "mysql-demo"
  MYSQL_PORT: "3306"
  MYSQL_USER: "user"
  MYSQL_DBNAME: "counter_db"


---

# backend-secret.yaml
# this file has been generated in the project https://github.com/eistin/demo-ansible-k8s

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secret
  namespace: demo-app
spec:
  encryptedData:
    MYSQL_PASSWORD: AgCwW5ZBai+QAtteUTea9xwD4kXIShV0o9pMTwxockCb6x6Ci2lAZqU3F6RwlGSvJuuRmt+VUcVFIQOVvKifon/pwHClHhhRzR9X07Ks4vLfp8g1tifP7RwailvkEYP4B2vH7FmPa4A9SK/LBIzBr3+W8Cl1M+swxmeDCchnp13vo8U/eUvC9DOjU0iQ/RPJn2cG3/tr9+Kyc0yI8TMkS3wyZD2BBt2QufY7NuTMKmOiYJsgL03bbRa5fAlrOV6ZgfXf/Q1CCZdSGD6XVrpIxgFgSYXzApK4gIGHyza0VxbB3kz7BtTgdXuHk2EqSMO/m2cxUm0z6UeQ5IAQBLZHgT6qEGD8m1fqB4t/wqeKCIo3orfXPNEbOG13Xu2LGAwEgW5+mhNtfk0G12A9UwzLbIp6mN1CJq9oJQ989rijzi9gCVj6eLCgG4hWOMM3nZFopixNh+iCXqkNTZHbLFO8MiAp6BGLhGpJGMIQRosqUPCknO9s+uk052ybXyGUzSJLDwkjUBN9zRTTXBE5rk9+wEtkl3zNmvgykaBVUZdmAOPm496PIXaVQQTl0heHtnpeDm0/yE9O7wc/OckNOZOsJ3jgvTkKC2wrQNhHdOEneBZmsk3G6meE843rtgqj2hVpomp94z2vPvCQTrqflrkPAFDsp+re9cEbR68Q/R3d5eSZk6mPC/r2xrSmhcIzcs2hxCI/uL8f
  template:
    metadata:
      creationTimestamp: null
      name: backend-secret
      namespace: demo-app
    type: Opaque
