# backend-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
        containers:
          - name: backend
            image: edwinistin/kubernetes-app-image:backend
            imagePullPolicy: Always
            ports:
              - containerPort: 8080
            resources:
              limits:
                cpu: "0.5"
                memory: "512Mi"
              requests:
                cpu: "0.1"
                memory: "256Mi"
            livenessProbe:
              httpGet:
                path: /
                port: 8080
              initialDelaySeconds: 3
              periodSeconds: 3
              timeoutSeconds: 1
              successThreshold: 1
              failureThreshold: 3
            readinessProbe:
              httpGet:
                path: /
                port: 8080
              initialDelaySeconds: 3
              periodSeconds: 3
              timeoutSeconds: 1
              successThreshold: 1
              failureThreshold: 3
---

# backend-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP