apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}
  labels: {{- include "backend.labels" . | nindent 4 }}
data:
  MYSQL_HOST: "{{ .Values.env.mySqlHost }}"
  MYSQL_PORT: "{{ .Values.env.mySqlPort }}"
  MYSQL_USER: "{{ .Values.env.mySqlUser }}"
  MYSQL_DBNAME: "{{ .Values.env.mySqlDbName }}"
