version: "3"

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: counter_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  backend:
    build:
      context: ./backend
    ports:
      - "8081:8080"
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DBNAME: counter_db

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
    ports:
      - "8000:80"
    depends_on:
      nginx:
        condition: service_started
      db:
        condition: service_healthy
    environment:
      API_URL: http://localhost:8080

volumes:
  db:
  mysql_data:
